# Script for checking out sources and storing it as an artifact
# The artifact name is "modules"
#
# Template Parameters:
#   builder: cctbx builder (e.g. cctbx, phaser, etc.)
#
# Parameters:
#   flags: <empty>, --use-conda
#   optimization: <empty>, 0, 1, 2, 3

jobs:
- job: modules${{ parameters.optimization }}
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 90

  steps:

  # download sources
  - checkout: cctbx_project
    path: ./modules/cctbx_project

  - script: |
      cd $(Pipeline.Workspace)
      ln -s modules/cctbx_project/libtbx/auto_build/bootstrap.py
    displayName: Link bootstrap.py

  - script: |
      cd $(Pipeline.Workspace)
      python bootstrap.py hot update --builder=${{ parameters.builder }} ${{ parameters.flags }}
    displayName: Download sources

  # change optimization level (linux, macOS)
  - script: |
      cd $(Pipeline.Workspace)/modules/cctbx_project/libtbx
      # Remove -ffast-math
      sed -i 's/-ffast-math//g' SConscript
      # Change -O level
      sed -i 's/-O3/-O${{ parameters.optimization }}/g' SConscript
    displayName: Changing optimization (linux, macOS)
    condition: or(eq('${{ parameters.optimization }}', 0), eq('${{ parameters.optimization }}', 1), eq('${{ parameters.optimization }}', 2), eq('${{ parameters.optimization }}', 3))

  # change optimization level (Windows)
  - script: |
      cd $(Pipeline.Workspace)/modules/cctbx_project/libtbx
      # Remove /fp:fast
      sed -i 's/\/fp:fast//g' SConscript
      # Change /O2 to /O1
      sed -i 's/\/O2/\/O1/g' SConscript
    displayName: Changing optimization (Windows)
    condition: or(eq('${{ parameters.optimization }}', 0), eq('${{ parameters.optimization }}', 1))

  # preserve permissions
  - script: |
      cd $(Pipeline.Workspace)
      tar -chf modules.tar modules
    displayName: Build tarball

  # publish artifact
  - publish: $(Pipeline.Workspace)/modules.tar
    artifact: modules${{ parameters.optimization }}
    continueOnError: true
