# Script for nightly build of phaser

# no continuous integration builds or pull requests
trigger: none
pr: none

# Daily builds
schedules:
- cron: '0 2 * * *'
  displayName: Daily test for phaser
  branches:
    include:
    - master

resources:
  repositories:
    - repository: cctbx_project
      type: github
      name: phenix-project/cctbx_project
      endpoint: phenix-project
  pipelines:
  - pipeline: build_cache
    source: 'phaser_regression'
  - pipeline: data_cache
    project: cctbx_project
    source: 'Update data cache'
  - pipeline: cctbx_build_cache
    project: cctbx_project
    source: 'Update build cache'

parameters:
  - name: builder
    displayName: cctbx builder
    type: string
    default: phaser
  - name: test_module
    displayName: module to test
    type: string
    default: phaser_regression
  - name: pipeline
    displayName: pipeline name
    type: string
    default: phaser_regression

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ../download-source.yml

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ../full-build.yml
      parameters:
        modules: modules
