# Script for nightly build of phaser

# no continuous integration builds or pull requests
trigger: none
pr: none

# Daily builds
schedules:
- cron: '0 2 * * *'
  displayName: Daily test for phaser
  branches:
    include:
    - master

resources:
  repositories:
    - repository: cctbx_project
      type: github
      name: phenix-project/cctbx_project
      endpoint: phenix-project
  pipelines:
  - pipeline: build_cache
    source: 'phaser_regression'
  - pipeline: data_cache
    project: cctbx_project
    source: 'Update data cache'
  - pipeline: cctbx_build_cache
    project: cctbx_project
    source: 'Update build cache'

stages:
- stage: Preparation
  displayName: Download
  jobs:
    - template: ../download-source.yml
      parameters:
        builder: phaser

- stage: Build
  displayName: Build and test
  dependsOn: Preparation
  jobs:
    - template: ../full-build.yml
      parameters:
        modules: modules
        pipeline: phaser_regression
        builder: phaser
        test_module: phaser_regression
